using PKHeX.Core;

namespace PokemonManager.Core;

/// <summary>PKHeX legality settings for games running on (emulated) original hardware.</summary>
public static class Legality
{
    /// <summary>
    /// PKHeX assumes Gen 1/2 Pokémon came through the 3DS Virtual Console unless told otherwise, which makes
    /// GB-era event Pokémon (e.g. the Nintendo event Mews) look illegal. These saves are cartridge games.
    /// </summary>
    public static void UseCartridgeEra()
    {
        ParseSettings.AllowEraCartGB = true;
        ParseSettings.AllowEraCartGBA = true;
    }

    public static bool IsLegal(PKM pk) => new LegalityAnalysis(pk).Valid;

    /// <summary>Checks a Pokémon as it would sit in <paramref name="sav"/>: its trainer, game and era.</summary>
    public static bool IsLegal(PKM pk, SaveFile sav)
    {
        For(sav);
        return IsLegal(pk);
    }

    /// <summary>
    /// Points PKHeX's legality checks at this save (the trainer receiving Pokémon, and the cartridge era
    /// for Gen 1/2 games).
    /// </summary>
    public static void For(SaveFile sav)
    {
        ParseSettings.InitFromSaveFileData(sav);
        if (sav.Generation <= 2)
            UseCartridgeEra();
    }

    public static string FirstProblem(PKM pk)
    {
        var report = new LegalityAnalysis(pk).Report();
        return report.Split('\n', StringSplitOptions.RemoveEmptyEntries).FirstOrDefault()?.Trim() ?? "";
    }
}

/// <summary>
/// Gives out event Pokémon the way the original distributions did: each recipient got their own Pokémon,
/// with its PID, nature, IVs (and so stats), gender and so on generated by the distribution's own method.
/// Every Pokémon handed out is checked with PKHeX's legality analysis first.
/// </summary>
public static class EventPokemon
{
    /// <summary>Tries per gift. PKHeX's generators almost always produce a legal Pokémon first time.</summary>
    public const int Attempts = 20;

    public enum Source
    {
        /// <summary>Freshly generated from the distribution's event data.</summary>
        Generated,
        /// <summary>One of the gallery's recorded copies (for events PKHeX can't regenerate).</summary>
        GalleryCopy,
        /// <summary>The file as it is, for Pokémon that weren't generated per recipient (e.g. a traded-out Pokémon).</summary>
        File,
    }

    public sealed record Result(PKM? Pokemon, bool Legal, Source Source, string Message)
    {
        public static Result Fail(string message) => new(null, false, Source.File, message);
    }

    /// <summary>
    /// Whether PKHeX matched the Pokémon to an event that generated a new Pokémon for every recipient
    /// (Mystery Gifts, GB/GBA event distributions, My Pokémon Ranch gifts, Dream World encounters).
    /// </summary>
    public static bool IsPerRecipient(IEncounterable encounter) => encounter is MysteryGift
        or EncounterGift1 or EncounterGift2 or EncounterGift3 or EncounterGift3Colo or EncounterGift3NY
        or EncounterTrade4RanchGift or EncounterStatic5Entree;

    /// <summary>A freshly generated, legal copy of the event <paramref name="encounter"/> for this save, or null.</summary>
    public static PKM? Generate(IEncounterable encounter, SaveFile sav)
    {
        if (encounter is not IEncounterConvertible convertible)
            return null;
        for (int i = 0; i < Attempts; i++)
        {
            PKM pk;
            try
            {
                pk = convertible.ConvertToPKM(sav);
            }
            catch (Exception)
            {
                continue;
            }
            if (ForSave(pk, sav) is { } ready && Legality.IsLegal(ready, sav))
                return ready;
        }
        return null;
    }

    /// <summary>
    /// The Pokémon to give for a gallery Pokémon file: a new one generated from its event when PKHeX knows
    /// the event, else a random legal copy of the same distribution from the gallery, else the file itself.
    /// </summary>
    public static Result FromGallery(GalleryArchive gallery, GalleryEntry entry, SaveFile sav, Random? random = null)
    {
        Legality.For(sav);
        random ??= Random.Shared;
        var file = gallery.Load(entry)?.Pokemon;
        if (file is null)
            return Result.Fail("That gallery file couldn't be read.");

        // The file is judged as the gallery's copy; what's handed out is judged for this save.
        Legality.UseCartridgeEra();
        var analysis = new LegalityAnalysis(file);
        bool perRecipient = analysis.Valid && IsPerRecipient(analysis.EncounterMatch);
        if (perRecipient && Generate(analysis.EncounterMatch, sav) is { } generated)
            return new Result(generated, true, Source.Generated, "");

        if (perRecipient)
        {
            // PKHeX can't recreate a few distributions (e.g. the Berry Glitch Shiny Zigzagoon's RNG), so hand
            // out one of the real copies the gallery has recorded instead.
            var key = GalleryNames.DisplayTitle(entry.Title);
            var copies = gallery.Entries
                .Where(e => e.Kind == GalleryKind.Pokemon && e.Folder == entry.Folder && e.Language == entry.Language
                            && string.Equals(GalleryNames.DisplayTitle(e.Title), key, StringComparison.OrdinalIgnoreCase))
                .OrderBy(_ => random.Next())
                .ToList();
            foreach (var copy in copies)
            {
                if (gallery.Load(copy)?.Pokemon is { } pk && ForSave(pk, sav) is { } ready && Legality.IsLegal(ready, sav))
                    return new Result(ready, true, Source.GalleryCopy, "");
            }
        }

        var converted = ForSave(file, sav);
        if (converted is null)
            return Result.Fail($"{Names.Species(file)} can't be added to {Names.Game(sav)}.");
        bool legal = Legality.IsLegal(converted, sav);
        return new Result(converted, legal, Source.File, legal ? "" : Legality.FirstProblem(converted));
    }

    /// <summary>The Pokémon converted to the save's format (Pal Park etc. for older files), or null if it can't go there.</summary>
    private static PKM? ForSave(PKM pk, SaveFile sav)
    {
        var check = TransferService.Prepare(pk, sav, allowUnofficial: false, out var prepared);
        return check.Ok ? prepared?.Converted : null;
    }
}
