#!/usr/bin/env python3
"""Regenerates src/PokemonManager/Core/VanillaRoms.g.cs from No-Intro DATs.

Usage: scripts/update-vanilla-roms.py <libretro-database>/metadat/no-intro

The DATs come from https://github.com/libretro/libretro-database (metadat/no-intro).
Only retail dumps of the main-series games are kept: betas, prototypes, kiosk demos,
pirate and unlicensed entries are dropped.
"""
import os
import re
import sys

DATS = {
    "Nintendo - Game Boy.dat": "GB",
    "Nintendo - Game Boy Color.dat": "GBC",
    "Nintendo - Game Boy Advance.dat": "GBA",
    "Nintendo - Nintendo DS.dat": "NDS",
}

# Main-series game codes (first three letters; the fourth is the region).
SERIALS = {
    "AXV": "Ruby", "AXP": "Sapphire", "BPE": "Emerald", "BPR": "FireRed", "BPG": "LeafGreen",
    "ADA": "Diamond", "APA": "Pearl", "CPU": "Platinum", "IPK": "HeartGold", "IPG": "SoulSilver",
    "IRB": "Black", "IRA": "White", "IRE": "Black 2", "IRD": "White 2",
}

EXCLUDED_TAGS = re.compile(r"\((Beta|Proto|Possible Proto|Demo|Kiosk|Debug|Sample|Pirate|Unl|Hack|Aftermarket)\b[^)]*\)")
# Game Boy / Color spin-offs that share the "Pokemon -" prefix.
GB_SPINOFFS = re.compile(r"Pinball|Puzzle|Card|Picross|Panepon|Trading|Stadium", re.I)
GAME = re.compile(r'^game \($.*?^\)$', re.S | re.M)
ROM = re.compile(r'rom \( name "([^"]+)" size (\d+) crc ([0-9A-Fa-f]{8})(?:.*?serial "([^"]+)")?')


def entries(folder):
    for dat, system in DATS.items():
        text = open(os.path.join(folder, dat), encoding="utf-8").read()
        for block in GAME.findall(text):
            for rom in ROM.finditer(block):
                name, size, crc, serial = rom.groups()
                if not name.startswith(("Pokemon - ", "Pocket Monsters ")):
                    continue
                if EXCLUDED_TAGS.search(name):
                    continue
                if system in ("GBA", "NDS"):
                    if not serial:
                        m = re.search(r'serial "([^"]+)"', block)
                        serial = m.group(1) if m else ""
                    if serial[:3] not in SERIALS:
                        continue
                elif GB_SPINOFFS.search(name):
                    continue
                yield int(crc, 16), int(size), os.path.splitext(name)[0]


def main():
    rows = sorted(set(entries(sys.argv[1])), key=lambda r: r[2])
    out = os.path.join(os.path.dirname(__file__), "..", "src", "PokemonManager", "Core", "VanillaRoms.g.cs")
    with open(out, "w", encoding="utf-8", newline="\n") as f:
        f.write("// <auto-generated>\n")
        f.write("// Generated by scripts/update-vanilla-roms.py from the No-Intro DATs in libretro-database.\n")
        f.write("// Do not edit by hand.\n")
        f.write("// </auto-generated>\n\n")
        f.write("namespace PokemonManager.Core;\n\n")
        f.write("internal static partial class VanillaRoms\n{\n")
        f.write("    /// <summary>CRC32, size and No-Intro name of every retail main-series Pokémon ROM.</summary>\n")
        f.write("    private static readonly (uint Crc, long Size, string Name)[] Dumps =\n    [\n")
        for crc, size, name in rows:
            f.write(f'        (0x{crc:08X}, {size}, "{name}"),\n')
        f.write("    ];\n}\n")
    print(f"{len(rows)} ROMs written to {os.path.normpath(out)}")


if __name__ == "__main__":
    main()
